/*
 * Copyright (c) 2019 ARM Limited. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "oma_lwm2m_object_defs.h"
#include "lwm2m_registry_meta.h"
#include <inttypes.h>

#ifdef USER_OMA_OBJECT_FILE
#pragma message ( "using user OMA object config file" )
#include USER_OMA_OBJECT_FILE
#endif


const lwm2m_resource_meta_definition_t OMA_LWM2M_RESOURCE_DEFS_OBJECT_10252[] = {
    LWM2M_RESOURCE_DEFINITION(1, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_OPAQUE, "Package"),
    LWM2M_RESOURCE_DEFINITION(2, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "State"),
    LWM2M_RESOURCE_DEFINITION(3, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "UpdateResult"),
    LWM2M_RESOURCE_DEFINITION(5, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "PkgName"),
    LWM2M_RESOURCE_DEFINITION(6, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "PkgVersion")
};


const lwm2m_resource_meta_definition_t OMA_LWM2M_RESOURCE_DEFS_OBJECT_10255[] = {
    LWM2M_RESOURCE_DEFINITION(0, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Protocolsupported"),
    LWM2M_RESOURCE_DEFINITION(1, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OPAQUE, "BootloaderHash"),
    LWM2M_RESOURCE_DEFINITION(2, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OPAQUE, "OEMBootloaderHash"),
    LWM2M_RESOURCE_DEFINITION(3, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OPAQUE, "Vendor"),
    LWM2M_RESOURCE_DEFINITION(4, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OPAQUE, "Class"),
    LWM2M_RESOURCE_DEFINITION(5, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OPAQUE, "DeviceId")
};


const lwm2m_resource_meta_definition_t OMA_LWM2M_RESOURCE_DEFS_OBJECT_3[] = {
    LWM2M_RESOURCE_DEFINITION(0, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Manufacturer"),
    LWM2M_RESOURCE_DEFINITION(1, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Model Number"),
    LWM2M_RESOURCE_DEFINITION(2, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Serial Number"),
    LWM2M_RESOURCE_DEFINITION(3, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Firmware Version"),
    LWM2M_RESOURCE_DEFINITION(4, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_NONE, "Reboot"),
    LWM2M_RESOURCE_DEFINITION(5, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_NONE, "Factory Reset"),
    LWM2M_RESOURCE_DEFINITION(6, LWM2M_RESOURCE_MULTIPLE_INSTANCES, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Available Power Sources"),
    LWM2M_RESOURCE_DEFINITION(7, LWM2M_RESOURCE_MULTIPLE_INSTANCES, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Power Source Voltage"),
    LWM2M_RESOURCE_DEFINITION(8, LWM2M_RESOURCE_MULTIPLE_INSTANCES, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Power Source Current"),
    LWM2M_RESOURCE_DEFINITION(9, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Battery Level"),
    LWM2M_RESOURCE_DEFINITION(10, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Memory Free"),
    LWM2M_RESOURCE_DEFINITION(11, LWM2M_RESOURCE_MULTIPLE_INSTANCES, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Error Code"),
    LWM2M_RESOURCE_DEFINITION(12, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_NONE, "Reset Error Code"),
    LWM2M_RESOURCE_DEFINITION(13, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_TIME, "Current Time"),
    LWM2M_RESOURCE_DEFINITION(14, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_STRING, "UTC Offset"),
    LWM2M_RESOURCE_DEFINITION(15, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_STRING, "Timezone"),
    LWM2M_RESOURCE_DEFINITION(16, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Supported Binding and Modes"),
    LWM2M_RESOURCE_DEFINITION(17, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Device Type"),
    LWM2M_RESOURCE_DEFINITION(18, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Hardware Version"),
    LWM2M_RESOURCE_DEFINITION(19, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_STRING, "Software Version"),
    LWM2M_RESOURCE_DEFINITION(20, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Battery Status"),
    LWM2M_RESOURCE_DEFINITION(21, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Memory Total"),
    LWM2M_RESOURCE_DEFINITION(22, LWM2M_RESOURCE_MULTIPLE_INSTANCES, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_OBJLNK, "ExtDevInfo")
};


const lwm2m_resource_meta_definition_t OMA_LWM2M_RESOURCE_DEFS_OBJECT_0[] = {
    LWM2M_RESOURCE_DEFINITION(0, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_STRING, "LWM2M  Server URI"),
    LWM2M_RESOURCE_DEFINITION(1, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_BOOLEAN, "Bootstrap-Server"),
    LWM2M_RESOURCE_DEFINITION(2, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_INTEGER, "Security Mode"),
    LWM2M_RESOURCE_DEFINITION(3, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_OPAQUE, "Public Key or Identity"),
    LWM2M_RESOURCE_DEFINITION(4, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_OPAQUE, "Server Public Key"),
    LWM2M_RESOURCE_DEFINITION(5, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_OPAQUE, "Secret Key"),
    LWM2M_RESOURCE_DEFINITION(6, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_INTEGER, "SMS Security Mode"),
    LWM2M_RESOURCE_DEFINITION(7, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_OPAQUE, "SMS Binding Key Parameters"),
    LWM2M_RESOURCE_DEFINITION(8, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_OPAQUE, "SMS Binding Secret Key(s)"),
    LWM2M_RESOURCE_DEFINITION(9, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_STRING, "LwM2M Server SMS Number"),
    LWM2M_RESOURCE_DEFINITION(10, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_INTEGER, "Short Server ID"),
    LWM2M_RESOURCE_DEFINITION(11, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_INTEGER, "Client Hold Off Time"),
    LWM2M_RESOURCE_DEFINITION(12, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_NONE, LWM2M_RESOURCE_TYPE_INTEGER, "Bootstrap-Server Account Timeout")
};


const lwm2m_resource_meta_definition_t OMA_LWM2M_RESOURCE_DEFS_OBJECT_1[] = {
    LWM2M_RESOURCE_DEFINITION(0, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_R, LWM2M_RESOURCE_TYPE_INTEGER, "Short Server ID"),
    LWM2M_RESOURCE_DEFINITION(1, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_INTEGER, "Lifetime"),
    LWM2M_RESOURCE_DEFINITION(2, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_INTEGER, "Default Minimum Period"),
    LWM2M_RESOURCE_DEFINITION(3, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_INTEGER, "Default Maximum Period"),
    LWM2M_RESOURCE_DEFINITION(4, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_NONE, "Disable"),
    LWM2M_RESOURCE_DEFINITION(5, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_OPTIONAL, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_INTEGER, "Disable Timeout"),
    LWM2M_RESOURCE_DEFINITION(6, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_BOOLEAN, "Notification Storing When Disabled or Offline"),
    LWM2M_RESOURCE_DEFINITION(7, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_RW, LWM2M_RESOURCE_TYPE_STRING, "Binding"),
    LWM2M_RESOURCE_DEFINITION(8, LWM2M_RESOURCE_SINGLE_INSTANCE, LWM2M_RESOURCE_MANDATORY, LWM2M_RESOURCE_OPERATIONS_E, LWM2M_RESOURCE_TYPE_NONE, "Registration Update Trigger")
};


const lwm2m_object_meta_definition_t OMA_LWM2M_OBJECT_DEFS[] =
{
    LWM2M_OBJECT_DEFINITION(10252, LWM2M_OBJECT_SINGLE_INSTANCE, LWM2M_OBJECT_MANDATORY, "Manifest", 5, OMA_LWM2M_RESOURCE_DEFS_OBJECT_10252),\
    LWM2M_OBJECT_DEFINITION(10255, LWM2M_OBJECT_SINGLE_INSTANCE, LWM2M_OBJECT_MANDATORY, "Device Metadata", 6, OMA_LWM2M_RESOURCE_DEFS_OBJECT_10255),\
    LWM2M_OBJECT_DEFINITION(3, LWM2M_OBJECT_SINGLE_INSTANCE, LWM2M_OBJECT_MANDATORY, "Device", 23, OMA_LWM2M_RESOURCE_DEFS_OBJECT_3),\
    LWM2M_OBJECT_DEFINITION(0, LWM2M_OBJECT_MULTIPLE_INSTANCES, LWM2M_OBJECT_MANDATORY, "LWM2M Security", 13, OMA_LWM2M_RESOURCE_DEFS_OBJECT_0),\
    LWM2M_OBJECT_DEFINITION(1, LWM2M_OBJECT_MULTIPLE_INSTANCES, LWM2M_OBJECT_MANDATORY, "LwM2M Server", 9, OMA_LWM2M_RESOURCE_DEFS_OBJECT_1),
#ifdef USER_OMA_OBJECTS
USER_OMA_OBJECTS,
#endif
};



const uint16_t OMA_LWM2M_OBJECT_DEFS_SIZE = sizeof(OMA_LWM2M_OBJECT_DEFS) / sizeof(lwm2m_object_meta_definition_t);

